-- NUM(INT) / ID / PASS / NAME / ADDR / PHONE / GENDER / AGE(INT)
CREATE TABLE TEST_MEMBER(
	NUM INT PRIMARY KEY AUTO_INCREMENT,
	ID VARCHAR(30) UNIQUE NOT NULL,
	PASS VARCHAR(30) NOT NULL,
	NAME VARCHAR(50),
	ADDR TEXT,
	PHONE VARCHAR(20),
	GENDER VARCHAR(10),
	AGE INT(3)
);

-- 관리자 계정 추가 - ID : ADMIN , PASS - ADMIN , NAME - MASTER
INSERT INTO TEST_MEMBER 
VALUES(NULL,'ADMIN','ADMIN','MASTER',
	   '부산광역시','01011111111','남성',30);
	   
SELECT * FROM TEST_MEMBER;

COMMIT;
